[project]
org-name = "ballerina"
version = "@toml.version@"

[platform]
target = "java11"

    [[platform.libraries]]
    artifactId = "io"
    version = "@project.version@"
    path = "../java.arrays-test-utils/build/libs/java.arrays-test-utils-@project.version@.jar"
    groupId = "org.ballerinalang.stdlib.java.arrays.testutils"
    modules = ["java.arrays"]
    scope = "testOnly"
    
