[package]
org = "ballerina"
name = "jarrays"
version = "@toml.version@"

[[platform.java11.dependency]]
path = "../jarrays-test-utils/build/libs/jarrays-test-utils-@project.version@.jar"
groupId = "org.ballerinalang.stdlib.jarrays.testutils"
artifactId = "jarrays-test-utils"
version = "@project.version@"
scope = "testOnly"
